# To execute this docker-compose yml file use `docker-compose up`
# Add the `-d` flag at the end for detached execution
version: "3"
services:
  hub:
    image: selenium/hub:3.14
    # port mapping to host
    ports:
    - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    # register to hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    depends_on:
      - hub
    # register to hub
    environment:
      - HUB_HOST=hub
