version: '3.7'
services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_volume:/data/db

volumes:
  mongodb_data_volume: