version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - "./:/usr/src/app/app"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  mongoexpress:
    image: "mongo-express"
    ports:
      - "8081:8081"
    depends_on:
      - mongo
